{{- if .Values.managerConfig.operatorScope.namespacedScope }}
{{ range .Values.managerConfig.operatorScope.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chart.fullname" $ }}-manager-role
  labels:
  {{- include "chart.labels" $ | nindent 4 }}
  namespace: {{ . }}
rules:
  {{- $.Files.Get "generated/rbac_manager_rules.yaml" | nindent 2}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chart.fullname" $ }}-manager-rolebinding
  labels:
  {{- include "chart.labels" $ | nindent 4 }}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "chart.fullname" $ }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" $ }}-controller-manager'
  namespace: '{{ $.Release.Namespace }}'
{{- end }}

{{- end }}