apiVersion: v2
name: lightrun-k8s-operator
description: A Helm chart for Lightrun k8s operator
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
icon: https://lightrun-public.s3.amazonaws.com/img/lightrun-logo.png

## Kubeversion due to "seccompProfile" in the controller deployment
kubeVersion: ">= 1.19.0"

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0 # Will be updated by CI pipeline



# ArtifactHub.io annotations
annotations:
  artifacthub.io/crds: |
    - kind: LightrunJavaAgent
      version: v1beta
      name: lightrunjavaagent
      shortName: lrja
      description: Custom resource describing Lightrun agent version, configuration and deployment that will be patched. Dependend on secret with few Lightrun key
  artifacthub.io/crdsExamples: |
      apiVersion: agents.lightrun.com/v1beta
      kind: LightrunJavaAgent
      metadata:
        name: example-cr 
      spec:
        initContainer:  
          image: "lightruncom/k8s-operator-init-java-agent-linux:1.8.5-init.1"
          sharedVolumeName: lightrun-agent-init
          sharedVolumeMountPath: "/lightrun"
        deploymentName: app  
        secretName: lightrun-secrets 
        serverHostname: app.lightrun.com
        agentEnvVarName: JAVA_TOOL_OPTIONS
        agentConfig:
          max_log_cpu_cost: "2"
        agentTags:
          - operator
          - example
          - 1.8.3
        containerSelector:
          - app
      ---
      apiVersion: v1
      metadata: 
        name: lightrun-secrets
      stringData:
        lightrun_key: <lightrun_key_from_ui>
        pinned_cert_hash: <pinned_cert_hash>
      kind: Secret
      type: Opaque

  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Operator repo
      url: https://github.com/lightrun-platform/lightrun-k8s-operator
    - name: CR example with explanation
      url: https://github.com/lightrun-platform/lightrun-k8s-operator/blob/main/examples/lightrunjavaagent.yaml
  artifacthub.io/maintainers: |
    - name: Lightrun devops team
      email: devopsdevops@lightrun.com 
    - name: LeonidP
      email: leonidp@lightrun.com 
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Basic Install
  artifacthub.io/prerelease: "false"
  
