# Default values for lightrun-javaagent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
javaAgents: []
## Examples
### Basic
#- The `my-service-1` does not use an `existingSecret` and instead the `agentPoolCredentials.apiKey` and `agentPoolCredentials.pinnedCertHash` are provided directly.

#- The `my-service-2` uses an `existingSecret` named `my-existing-secret`

#javaAgents:
#  - name: 'my-service-1'
#    namespace: 'my-namespace-1'
#    deploymentName: "my-deployment-1"
#    containerSelector:
#      - my-container-1
#    serverHostname: 'lightrun.example.com'
#    useSecretAsEnvVars: true
#    initContainer:
#      image: "lightruncom/k8s-operator-init-java-agent-linux:latest"
#    agentPoolCredentials:
#      existingSecret: ""
#      apiKey: "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
#      pinnedCertHash: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#    agentTags:
#      - env-production
#      - service-my-server
#      - region-us_east_1
#      - provider-aws
#  - name: 'my-service-2'
#    namespace: 'my-namespace-2'
#    initContainer:
#      image: "lightruncom/k8s-operator-init-java-agent-linux:latest"
#    deploymentName: "my-deployment-2"
#    containerSelector:
#      - my-container-2
#    serverHostname: 'lightrun.example.com'
#    useSecretAsEnvVars: true
#    agentPoolCredentials:
#      existingSecret: "my-existing-secret"
#      apiKey: ""
#      pinnedCertHash: ""
#    agentTags:
#      - env-production
#      - service-my-other-server
#      - region-us_east_1
#      - provider-aws

### Full

# - The `my-service-1` does not use an `existingSecret` and instead the `agentPoolCredentials.apiKey` and `agentPoolCredentials.pinnedCertHash` are provided directly.

# - The `my-service-2` uses an `existingSecret` named `my-existing-secret`

#javaAgents:
#  - name: 'my-service-1'
#    namespace: 'my-namespace-1'
#    deploymentName: "my-deployment-1"
#    containerSelector:
#      - my-container-1
#    serverHostname: 'lightrun.example.com'
#    useSecretAsEnvVars: true
#    agentEnvVarName: '_JAVA_OPTIONS'
#    agentConfig:
#      max_log_cpu_cost: "2"
#    agentCliFlags: "--lightrun_extra_class_path=<PATH_TO_JAR>:<PATH_TO_JAR>,lightrun_init_wait_time_ms"
#    initContainer:
#      image: "lightruncom/k8s-operator-init-java-agent-linux:latest"
#      sharedVolumeName: 'my-shared-volume'
#      sharedVolumeMountPath: '/mypath'
#    agentPoolCredentials:
#      existingSecret: ""
#      apiKey: "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
#      pinnedCertHash: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#    agentTags:
#      - env-production
#      - service-my-server
#      - region-us_east_1
#      - provider-aws
#  - name: 'my-service-2'
#    namespace: 'my-namespace-2'
#    initContainer:
#      image: "lightruncom/k8s-operator-init-java-agent-linux:latest"
#      sharedVolumeName: 'my-shared-volume'
#      sharedVolumeMountPath: '/mypath'
#    deploymentName: "my-deployment-2"
#    containerSelector:
#      - my-container-2
#    serverHostname: 'lightrun.example.com'
#    useSecretAsEnvVars: true
#    agentEnvVarName: 'JAVA_OPTS'
#    agentConfig:
#      max_log_cpu_cost: "2"
#    agentCliFlags: "--lightrun_extra_class_path=<PATH_TO_JAR>:<PATH_TO_JAR>,lightrun_init_wait_time_ms"
#    agentPoolCredentials:
#      existingSecret: "my-existing-secret"
#      apiKey: ""
#      pinnedCertHash: ""
#    agentTags:
#      - env-production
#      - service-my-other-server
#      - region-us_east_1
#      - provider-aws