apiVersion: agents.lightrun.com/v1beta
kind: LightrunJavaAgent
metadata:
  name: sample
spec:
  initContainer:
    image: "lightruncom/k8s-operator-init-java-agent-linux:latest"
    sharedVolumeName: lightrun-agent-init
    sharedVolumeMountPath: "/lightrun"
  deploymentName: sample-deployment  
  secretName: lightrun-secrets 
  serverHostname: dogfood.internal.lightrun.com
  useSecretsAsMountedFiles: false
  agentEnvVarName: JAVA_TOOL_OPTIONS
  agentConfig:
    max_log_cpu_cost: "2"
  agentTags:
    - k3s
    - ci
  agentName: "ci-k3s-agent"
  containerSelector:
    - app

