# permissions for end users to edit lightrunjavaagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: lightrunjavaagent-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lightrun-k8s-operator
    app.kubernetes.io/part-of: lightrun-k8s-operator
    
  name: lightrunjavaagent-editor-role
rules:
- apiGroups:
  - agents.lightrun.com
  resources:
  - lightrunjavaagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agents.lightrun.com
  resources:
  - lightrunjavaagents/status
  verbs:
  - get
