apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lightrun-k8s-operator
    app.kubernetes.io/part-of: lightrun-k8s-operator
    
  name: controller-manager
  namespace: system
