//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Lightrun

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitContainer) DeepCopyInto(out *InitContainer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitContainer.
func (in *InitContainer) DeepCopy() *InitContainer {
	if in == nil {
		return nil
	}
	out := new(InitContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LightrunJavaAgent) DeepCopyInto(out *LightrunJavaAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LightrunJavaAgent.
func (in *LightrunJavaAgent) DeepCopy() *LightrunJavaAgent {
	if in == nil {
		return nil
	}
	out := new(LightrunJavaAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LightrunJavaAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LightrunJavaAgentList) DeepCopyInto(out *LightrunJavaAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LightrunJavaAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LightrunJavaAgentList.
func (in *LightrunJavaAgentList) DeepCopy() *LightrunJavaAgentList {
	if in == nil {
		return nil
	}
	out := new(LightrunJavaAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LightrunJavaAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LightrunJavaAgentSpec) DeepCopyInto(out *LightrunJavaAgentSpec) {
	*out = *in
	if in.ContainerSelector != nil {
		in, out := &in.ContainerSelector, &out.ContainerSelector
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.InitContainer = in.InitContainer
	if in.AgentConfig != nil {
		in, out := &in.AgentConfig, &out.AgentConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AgentTags != nil {
		in, out := &in.AgentTags, &out.AgentTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LightrunJavaAgentSpec.
func (in *LightrunJavaAgentSpec) DeepCopy() *LightrunJavaAgentSpec {
	if in == nil {
		return nil
	}
	out := new(LightrunJavaAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LightrunJavaAgentStatus) DeepCopyInto(out *LightrunJavaAgentStatus) {
	*out = *in
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LightrunJavaAgentStatus.
func (in *LightrunJavaAgentStatus) DeepCopy() *LightrunJavaAgentStatus {
	if in == nil {
		return nil
	}
	out := new(LightrunJavaAgentStatus)
	in.DeepCopyInto(out)
	return out
}
