apiVersion: agents.lightrun.com/v1beta
kind: LightrunJavaAgent
metadata:
  name: sample
spec:
  initContainer:
    image: "lightruncom/k8s-operator-init-java-agent-linux:1.7.0-init.0"
    sharedVolumeName: lightrun-agent-init
    sharedVolumeMountPath: "/lightrun"
  workloadName: app
  workloadType: Deployment
  secretName: lightrun-secrets 
  serverHostname: <lightrun_server>  #for saas it will be app.lightrun.com
  useSecretAsEnvVars: true
  agentEnvVarName: JAVA_TOOL_OPTIONS
  agentConfig:
    max_log_cpu_cost: "2"
  agentTags:
    - operator
  agentName: "oper-test-agent"
  containerSelector:
    - app
---
apiVersion: v1
metadata: 
  name: lightrun-secrets
stringData:
  lightrun_key: <lightrun_key_from_ui>
  pinned_cert_hash: <pinned_cert_hash>
kind: Secret
type: Opaque
