{{ range .Values.javaAgents }}
{{- if not .agentPoolCredentials.existingSecret }}
---
apiVersion: v1
metadata:
  name: {{ .name }}-secret
  namespace: {{ .namespace }}
stringData:
  # Lightrun key you can take from the server UI at the "setup agent" step
  lightrun_key: {{ .agentPoolCredentials.apiKey }}
  # Server certificate hash. It is ensuring that agent is connected to the right Lightrun server
  pinned_cert_hash: {{ .agentPoolCredentials.pinnedCertHash }}
kind: Secret
type: Opaque
{{- end }}
{{- end }}
