apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-statefulset
  labels:
    app: stateful-app
spec:
  serviceName: "stateful-app"
  replicas: 1
  selector:
    matchLabels:
      app: stateful-app
  template:
    metadata:
      labels:
        app: stateful-app
    spec:
      containers:
        - name: app
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -Djava.net.preferIPv4Stack=true
          image: lightrun-k8s-operator-registry:5000/operator-demo-app:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          # volumeMounts:
          # - name: data
          #   mountPath: /data
        # Second container will be not patched, as not mentioned in the custom resource
        - name: non-patched-app
          image: lightruncom/operator-demo-app
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          # volumeMounts:
          # - name: data
          #   mountPath: /data
  # volumeClaimTemplates:
  # - metadata:
  #     name: data
  #   spec:
  #     accessModes: ["ReadWriteOnce"]
  #     resources:
  #       requests:
  #         storage: 1Gi
