# Due to https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: dummy_check
on:
  pull_request: 
    branches:
      - main
    paths:
      - 'lightrun-init-agent/**'
      - '.github/**'
      - 'docs/**'
      - 'grafana/**'
jobs:
  build:
    name: Build controller and install helm chart
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'